title: Pranav Balakrishnan
logo: /media/pranav_profile.jpeg
description:  
#show_downloads: true
theme: jekyll-theme-minimal
baseurl: "/portfolio"
collections:
  projects:
    output: true
  publications:
    output: true
