title: Pranav Balakrishnan
logo: /media/photo.jpg
description:  
#show_downloads: true
theme: jekyll-theme-minimal
baseurl: "/portfolio"
collections:
  projects:
    output: true
  publications:
    output: true
